networks:
  logintegrite-net:
    driver: bridge

volumes:
  postgres_data:

services:

  postgres:
    image: postgres:15-alpine
    container_name: logintegrite-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: logintegrite_db
      POSTGRES_USER: logintegrite_user
      POSTGRES_PASSWORD: LogInt2026Secure
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - logintegrite-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U logintegrite_user -d logintegrite_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: logintegrite-keycloak
    restart: unless-stopped
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/logintegrite_db
      KC_DB_USERNAME: logintegrite_user
      KC_DB_PASSWORD: LogInt2026Secure
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Admin2026ASCELC
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
      KC_HTTP_PORT: 8080
    ports:
      - "8180:8080"
    volumes:
      # On monte le dossier contenant ton fichier JSON dans le dossier d'import automatique de Keycloak
      - ./docker/keycloak:/opt/keycloak/data/import
    networks:
      - logintegrite-net
    depends_on:
      postgres:
        condition: service_healthy

  backend:
    build:
      context: ./backend/logintegrite-backend
      dockerfile: Dockerfile
    container_name: logintegrite-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./backend/logintegrite-backend:/app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://logintegrite-postgres:5432/logintegrite_db
      SPRING_DATASOURCE_USERNAME: logintegrite_user
      SPRING_DATASOURCE_PASSWORD: LogInt2026Secure
      
      # Alignement de l'issuer pour correspondre aux requêtes venant de ton Ubuntu (localhost)
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://localhost:8180/realms/logintegrite
      # URL interne pour que le backend télécharge les clés publiques de Keycloak
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://logintegrite-keycloak:8080/realms/logintegrite/protocol/openid-connect/certs
    networks:
      - logintegrite-net
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: logintegrite-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@asce-lc.bf
      PGADMIN_DEFAULT_PASSWORD: Admin2026
    ports:
      - "5050:80"
    networks:
      - logintegrite-net
    depends_on:
      postgres:
        condition: service_healthy
