spring.application.name=logintegrite-backend

# ── BASE DE DONNÉES ──────────────────────────────
spring.datasource.url=jdbc:postgresql://localhost:5432/logintegrite_db
spring.datasource.username=logintegrite_user
spring.datasource.password=LogInt2026Secure
spring.datasource.driver-class-name=org.postgresql.Driver

# ── JPA / HIBERNATE 7 ────────────────────────────
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true


# ── SÉCURITÉ KEYCLOAK JWT ────────────────────────
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/logintegrite
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/logintegrite/protocol/openid-connect/certs

# ── KEYCLOAK ADMIN REST API ─────────────────────────────
keycloak.admin.server-url=http://localhost:8180
keycloak.admin.realm=logintegrite
keycloak.admin.client-id=logintegrite-admin-api
keycloak.admin.client-secret=7XpmBaGZPqmo14tfPCEld9eDl6btbcWW




# ── SERVEUR ───────────────────────────────────────
server.port=8080
server.error.include-message=always
server.error.include-binding-errors=always

# ── UPLOAD FICHIERS ───────────────────────────────
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=500MB

# ── ACTUATOR ──────────────────────────────────────
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# ── LOGS (Configuration de Débuggage Ciblée) ──────
logging.level.bf.gov.ascelc=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
